### ISSUE TITLE
Login with username

### ISSUE THREAD

**Issue by hamidafghan** [taylornetwork/laravel-username-generator#12]
After the installation the package it is expected to be able to login with the username.

**Comment by samueljtaylor** [comment]
To use the username to login instead of the email you need to add the following to your `LoginController`

```php
public function username()
{
    return 'username';
}
```

See Username Customization in [Laravel Authentication Docs](https://laravel.com/docs/5.8/authentication#included-authenticating)

I'll add this to the readme.

If you tried that and it's still not working let me know.
