### ISSUE TITLE
How to get list of usernames available?

### ISSUE THREAD

**Issue by katesaikishore** [taylornetwork/laravel-username-generator#48]
According to the doc it generates a unique username but is there any way to get list of available usernames?

**Comment by samueljtaylor** [comment]
Hi @katesaikishore 

I'm assuming you mean if a user enters a name (or username) and it's unavailable to display other possible options that are available based on that username?

Kind of like if the username `samtaylor` was taken and it came back with a suggestion of 

```
samtaylor1
samtaylor2
samtaylor123
```

There isn't a way to do that currently, but definitely something I can look into.

**Comment by katesaikishore** [comment]
Yeah, The way when we give `samtaylor`, The suggestions should be displayed so that the user can pick his choice. Looking forward.

**Comment by samueljtaylor** [comment]
Okay makes sense. I'll see what I can do make that work.

**Comment by katesaikishore** [comment]
And one more thing. During suggestions, it should first check if the DB has samtaylor username exists as text formate if `no` username should be samtaylor[text formate] if `yes`, a username should **first** include a character **then** a number then **other** formates make developer pick their choice of order.

**Comment by samueljtaylor** [comment]
Hi @katesaikishore 
In order to keep this package simple and only with a single string return type I've decided to implement this via a separate package that works in conjunction with this one. Check out [taylornetwork/username-suggester](https://github.com/taylornetwork/username-suggester)

It's still in very early development but I'll be working on it and I've just released a very early version that you can check out now. I'm going to close this one but feel free to open a new one over there if you have any problems/suggestions.

Thanks
